<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>StardewCraft</AssemblyName>
    <RootNamespace>StardewCraft</RootNamespace>
    <Version>0.1.0</Version>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <EnableHarmony>false</EnableHarmony>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

</Project>
